package com.hdl.vivado

import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFile
import java.io.File

object VivadoUtils {
    
    fun collectHDLFiles(folder: VirtualFile): List<VirtualFile> {
        val files = mutableListOf<VirtualFile>()
        
        fun traverse(dir: VirtualFile) {
            for (child in dir.children) {
                if (child.isDirectory) {
                    traverse(child)
                } else if (child.extension in listOf("v", "vh", "sv", "svh", "vhd", "vhdl")) {
                    files.add(child)
                }
            }
        }
        
        traverse(folder)
        return files
    }

    fun generateVivadoTclScript(
        project: Project,
        projectName: String,
        projectPath: String,
        hdlFiles: List<VirtualFile>,
        settings: VivadoSettingsState
    ): String {
        val script = StringBuilder()
        
        script.appendLine("# Vivado TCL script generated by IntelliJ Plugin")
        script.appendLine("")
        script.appendLine("# Create project")
        script.appendLine("create_project $projectName \"$projectPath\" -force")
        script.appendLine("")
        
        // Set part or board
        if (settings.board.isNotBlank()) {
            script.appendLine("set_property board_part ${settings.board} [current_project]")
        } else {
            script.appendLine("set_property part ${settings.part} [current_project]")
        }
        script.appendLine("")
        
        // Add source files
        script.appendLine("# Add source files")
        for (file in hdlFiles) {
            val fileType = when (file.extension) {
                "vhd", "vhdl" -> "VHDL"
                else -> "Verilog"
            }
            script.appendLine("add_files -fileset sources_1 \"${file.path}\"")
            script.appendLine("set_property file_type $fileType [get_files \"${file.path}\"]")
        }
        script.appendLine("")
        
        script.appendLine("# Update compile order")
        script.appendLine("update_compile_order -fileset sources_1")
        script.appendLine("")
        
        return script.toString()
    }

    fun launchVivado(
        vivadoPath: String,
        workingDirectory: String,
        tclScript: String? = null,
        mode: String = "gui"
    ): Process {
        val command = mutableListOf(vivadoPath)
        
        if (mode == "batch") {
            command.add("-mode")
            command.add("batch")
        }
        
        if (tclScript != null) {
            val scriptFile = File.createTempFile("vivado_script_", ".tcl")
            scriptFile.writeText(tclScript)
            scriptFile.deleteOnExit()
            
            command.add("-source")
            command.add(scriptFile.absolutePath)
        }
        
        val processBuilder = ProcessBuilder(command)
        processBuilder.directory(File(workingDirectory))
        
        return processBuilder.start()
    }

    fun findVivadoProject(folder: VirtualFile): VirtualFile? {
        for (child in folder.children) {
            if (child.extension == "xpr") {
                return child
            }
        }
        return null
    }
}
