package com.hdl.vivado.catalog

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Tests for the UG835 catalogue.
 *
 * The index is generated by tools/extract_ug835.py from a 2576-page PDF, so the parse is the
 * fragile part: a layout change in a future revision shows up here as a collapsed entry count
 * or a curated name that no longer resolves, rather than as a silently half-empty catalogue
 * shipped to users.
 */
class VivadoCommandCatalogTest {

    private val all = VivadoCommandCatalog.all

    // -------------------------------------------------------------------------
    // The generated index
    // -------------------------------------------------------------------------

    @Test
    fun `the index loads the whole command reference`() {
        // 770 entries parse from the current UG835; a big drop means the extractor's
        // entry heuristic stopped matching the document layout.
        assertTrue(all.size >= 700, "only ${all.size} commands parsed from ug835-index.tsv")
    }

    @Test
    fun `command names are unique`() {
        val dupes = all.groupBy { it.name }.filterValues { it.size > 1 }.keys
        assertTrue(dupes.isEmpty(), "duplicate catalogue entries: $dupes")
    }

    @Test
    fun `every entry has a name and a syntax line`() {
        for (entry in all) {
            assertTrue(entry.name.isNotBlank(), "blank command name in the index")
            assertTrue(entry.syntax.isNotBlank(), "${entry.name} has no syntax line")
            // Not startsWith(name): UG835 files report_noc under the "report_noc_qos" heading,
            // so a syntax head may name a sibling command — but it must be one we indexed,
            // otherwise the extractor has stitched two entries together.
            val head = entry.syntax.substringBefore(' ')
            assertNotNull(VivadoCommandCatalog.byName(head), "${entry.name}: syntax head '$head' is not indexed")
        }
    }

    @Test
    fun `option flags survive extraction as plain hyphens`() {
        // UG835 renders flags with U+2011 NON-BREAKING HYPHEN; Tcl needs '-'.
        val create = VivadoCommandCatalog.byName("create_clock")
        assertNotNull(create)
        assertTrue(create.syntax.contains("-period"), create.syntax)
        assertTrue(all.none { '‑' in it.syntax }, "a non-breaking hyphen leaked into the index")
    }

    // -------------------------------------------------------------------------
    // Curated tiers
    // -------------------------------------------------------------------------

    @Test
    fun `every curated core command exists in the reference`() {
        // Catches a typo in ug835-tier-core.txt, and catches AMD renaming a command
        // out from under the curation on a UG835 upgrade.
        val core = all.filter { it.tier == VivadoCommandCatalog.Tier.CORE }.map { it.name }.toSet()
        val curated = javaClass.getResourceAsStream("/vivado/ug835-tier-core.txt")!!
            .bufferedReader().useLines { lines ->
                lines.map { it.substringBefore('#').trim() }.filter { it.isNotEmpty() }.toList()
            }
        val unresolved = curated.filterNot { it in core }
        assertTrue(unresolved.isEmpty(), "curated core names not found in UG835: $unresolved")
    }

    @Test
    fun `the three tiers are all populated and roughly the intended size`() {
        val byTier = all.groupingBy { it.tier }.eachCount()
        val core = byTier[VivadoCommandCatalog.Tier.CORE] ?: 0
        val extended = byTier[VivadoCommandCatalog.Tier.EXTENDED] ?: 0
        val rest = byTier[VivadoCommandCatalog.Tier.REST] ?: 0
        assertTrue(core in 80..140, "CORE is $core, expected roughly 100")
        assertTrue(extended in 250..400, "EXTENDED is $extended, expected roughly 300")
        assertTrue(rest > 100, "REST is $rest, expected the long tail")
    }

    @Test
    fun `flow commands land in core and device accessors do not`() {
        assertEquals(VivadoCommandCatalog.Tier.CORE, VivadoCommandCatalog.byName("launch_runs")?.tier)
        assertEquals(VivadoCommandCatalog.Tier.CORE, VivadoCommandCatalog.byName("create_bd_cell")?.tier)
        assertEquals(VivadoCommandCatalog.Tier.REST, VivadoCommandCatalog.byName("get_tiles")?.tier)
    }

    // -------------------------------------------------------------------------
    // Search
    // -------------------------------------------------------------------------

    @Test
    fun `an exact name is the first result`() {
        assertEquals("create_clock", VivadoCommandCatalog.search("create_clock").first().name)
        assertEquals("report_timing", VivadoCommandCatalog.search("report_timing").first().name)
    }

    @Test
    fun `all query tokens must match`() {
        val hits = VivadoCommandCatalog.search("bd cell").map { it.name }
        assertTrue("create_bd_cell" in hits, hits.take(10).toString())
        assertTrue("create_clock" !in hits, "unrelated command matched a two-token query")
    }

    @Test
    fun `rest commands stay out of an ordinary search but resolve by exact name`() {
        // get_tiles is a device accessor: noise in a keyword search, still runnable when named.
        val ordinary = VivadoCommandCatalog.search("tiles").map { it.name }
        assertTrue("get_tiles" !in ordinary, "a REST command leaked into a default-scope search")

        val widened = VivadoCommandCatalog.search("tiles", includeAll = true).map { it.name }
        assertTrue("get_tiles" in widened, "scope=all did not reach the REST tier")

        assertEquals("get_tiles", VivadoCommandCatalog.search("get_tiles").firstOrNull()?.name)
    }

    @Test
    fun `a category filter restricts the result set`() {
        val hits = VivadoCommandCatalog.search("create", category = "IPIntegrator")
        assertTrue(hits.isNotEmpty())
        assertTrue(hits.all { "IPIntegrator" in it.categories }, hits.map { it.name to it.categories }.toString())
    }

    @Test
    fun `core outranks extended for an equally good name match`() {
        val hits = VivadoCommandCatalog.search("write_")
        val firstCore = hits.indexOfFirst { it.tier == VivadoCommandCatalog.Tier.CORE }
        val firstExtended = hits.indexOfFirst { it.tier == VivadoCommandCatalog.Tier.EXTENDED }
        assertTrue(firstCore in 0 until firstExtended, "core=$firstCore extended=$firstExtended")
    }

    // -------------------------------------------------------------------------
    // Details and suggestions
    // -------------------------------------------------------------------------

    @Test
    fun `details carry the argument table for a sampled command`() {
        val details = VivadoCommandCatalog.details("create_clock")
        assertNotNull(details)
        assertTrue(details.contains("-period"), details.take(400))
        assertTrue(details.contains("Description"), details.take(400))
        assertTrue(details.contains("\n"), "detail text lost its line breaks")
    }

    @Test
    fun `details exist for every core command`() {
        val missing = all.filter { it.tier == VivadoCommandCatalog.Tier.CORE }
            .map { it.name }
            .filter { VivadoCommandCatalog.details(it).isNullOrBlank() }
        assertTrue(missing.isEmpty(), "no reference text for: $missing")
    }

    @Test
    fun `an unknown name has no details and gets suggestions`() {
        assertNull(VivadoCommandCatalog.details("no_such_command"))
        // wait_on_run is the classic near-miss: UG835 documents the plural form.
        assertTrue("wait_on_runs" in VivadoCommandCatalog.closestNames("wait_on_run"))
    }
}
